name: teste Web test
run-name: Test browser robot
on: [push]

jobs:
  webtest:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: instalar python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: instalar node
        uses: actions/setup-node@v3
        with:
          node-version: '19.1'

      - name: robot 
        run: |
          python -m pip install --upgrade pip
          pip install -U robotframework
          pip install -U robotframework-browser
          pip install -U robotframework-doctestlibrary
          sudo npm install @playwright/test
          sudo npx playwright install --with-deps
          rfbrowser init

      - name: Run RF Tests
        run: |
          robot -d ./results LogBrowser.robot

      - name: Upload Test
        if: always()
        uses: actions/upload-artifact@v3 
        with:
          name: Results-chromium/webkit
          path: ./results
          if-no-files-fond: ignore
          retention-days: 2
